repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint
        name: Check markdown formatting
        args: [--config, .markdownlint.json]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [--config-file, .yamllint.yml]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: markdownlint-fix
        name: Fix markdown issues automatically
        entry: bash -c 'markdownlint --fix "**/*.md" --ignore node_modules'
        language: system
        pass_filenames: false
        types: [markdown]
        verbose: true

      - id: fix-code-blocks
        name: Fix code blocks in markdown
        entry: ./scripts/fix_code_blocks.sh
        language: script
        pass_filenames: false
        verbose: true

      - id: fix-newlines
        name: Fix missing newlines
        entry: ./scripts/fix_newlines.sh
        language: script
        pass_filenames: false
        verbose: true

      - id: fix-list-numbering
        name: Fix ordered list numbering
        entry: ./scripts/fix_list_numbering.sh
        language: script
        pass_filenames: false
        verbose: true

      - id: fix-heading-levels
        name: Fix markdown heading levels
        entry: ./scripts/fix_heading_levels.sh
        language: script
        pass_filenames: false
        verbose: true
