name: Lint Scripts

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**.sh'
      - '**.lua'
      - '.github/workflows/scripts-lint.yml'
  pull_request:
    branches: [main]
    paths:
      - 'scripts/**.sh'
      - '**.lua'
      - '.github/workflows/scripts-lint.yml'

jobs:
  basic_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify scripts exist
        run: |
          if [ -d "scripts" ]; then
            echo "Scripts directory found"
            ls -la scripts/
            echo "Validation successful"
          else
            echo "Scripts directory not found, but that's okay"
            echo "Validation successful"
          fi
