name: Lint Scripts

on:
  push:
    branches: [main]
    paths:
      - '**.sh'
      - '**.lua'
      - '.github/workflows/scripts-lint.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.sh'
      - '**.lua'
      - '.github/workflows/scripts-lint.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/*.sh') != '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          find ./scripts -name "*.sh" -type f -print0 | xargs -0 -n1 shellcheck --severity=warning || true

  luacheck:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/*.lua') != '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Run luacheck
        run: luacheck .
